fix(setup): allow setup with github.com
go-vela/compiler pull request #239
Opened 2021-10-15 19:51 UTC by cognifloyd

This is based on https://github.com/go-vela/server/pull/480

Leaving `VELA_COMPILER_GITHUB_URL` unset or set to an empty string leads to an error:
```
{"level":"fatal","msg":"github-url (VELA_COMPILER_GITHUB_URL or COMPILER_GITHUB_URL) flag not specified","time":"2021-10-15T19:46:55Z"}
```

Setting `VELA_COMPILER_GITHUB_URL=https://github.com` leads to this error:
```
vela-server-7b48b49665-7gvrc server {"api-version":"v0.9.2","fields.time":"2021-10-15T17:51:31Z","ip":"<ip>","latency":428261303,"level":"error","method":"POST","msg":"Error #01: unable to process webhook: failed to get changeset for <org>/<repo>: Repositories.GetCommit returned error: GET https://github.com/api/v3/repos/<org>/<repo>/commits/<commit>?per_page=100: 404  []\n","path":"/webhook","status":500,"time":"2021-10-15T17:51:31Z","user-agent":"GitHub-Hookshot/3be241b"}
```

So, this PR allows the compiler to work with github.com instead of assuming that it is working with github enterprise.

2021-10-20 01:05 UTC, JordanSussman reviewed
update log lines

2021-10-21 20:42 UTC, JordanSussman commented on registry/github/github.go
> +			c.URL = strings.Trim(address, "/") + "/"
`strings.Trim(address, "/") + "/"` seems redundant since you are removing the `/` and immediately adding it back. Any particular reason this behavior is occuring?

2021-10-21 21:06 UTC, cognifloyd commented on registry/github/github.go
> +			c.URL = strings.Trim(address, "/") + "/"
I don't want to add multiple final "/". I could check to see if it's there and add it if not, but this seemed like a very concise way to ensure it ends in exactly one "/".

2021-10-21 21:08 UTC, cognifloyd commented on registry/github/github.go
> +			c.URL = strings.Trim(address, "/") + "/"
iow `VELA_COMPILER_GITHUB_URL` might end in a slash and it might not. This ensures that it ends in a slash.

2021-10-22 17:47 UTC, cognifloyd commented on registry/github/github.go
> +			c.URL = strings.Trim(address, "/") + "/"
Does this make sense, or would you prefer a different approach?

2021-10-25 19:54 UTC, jbrockopp requested changes

2021-10-25 19:54 UTC, jbrockopp commented on registry/github/github.go
> +			c.URL = strings.Trim(address, "/") + "/"
@JordanSussman @cognifloyd thoughts on [adopting the same approach](https://github.com/go-vela/server/blob/e1decd38da24fd49a36654de9954a0d84a69e446/source/github/opts.go#L22-L36) we took for the Vela server?

```go
		// set a default address for the client
		c.config.Address = defaultURL
		// set a default API address for the client
		c.config.API = defaultAPI

		// check if an address was provided
		if len(address) > 0 {
			// check if the address is equal to the defaults
			if !strings.EqualFold(c.config.Address, address) {
				c.config.Address = strings.TrimSuffix(address, "/")
				if !strings.Contains(c.config.Address, "https://github.com") {
					c.config.API = fmt.Sprintf("%s/%s", c.config.Address, "api/v3/")
				}
			}
		}
```

https://github.com/go-vela/server/blob/master/source/github/opts.go#L27-L36

2021-10-25 21:28 UTC, cognifloyd commented on registry/github/github.go
> +			c.URL = strings.Trim(address, "/") + "/"
okey dokey. I simplified it to follow the Vela server approach. I concatenated the strings though because we don't need to worry about converting types with `fmt.Sprintf`, so its easier to read without the Sprintf.

2021-10-25 21:40 UTC, jbrockopp approved these changes
LGTM

2021-10-25 22:29 UTC, JordanSussman approved these changes

2021-10-25 22:30 UTC, merged